In [17]:
import numpy as np

test = [
        {1, 2, 5},
        {1, 4, 5},
        {1, 3},
        {2, 3, 4},
        {2, 3, 5},
        {4, 5},
        {1, 3, 4, 5},
        {1, 2, 5},
        {1, 3, 5},
        {1}
        ]


def binary_matrix(list_of_sets):
  all_items = sorted(set().union(*list_of_sets))

  binary_matrix = np.zeros((len(list_of_sets), len(all_items)), dtype=int)

  for i, itemset in enumerate(list_of_sets):
      for j, item in enumerate(all_items):
          if item in itemset:
              binary_matrix[i][j] = 1

  print("Binary matrix:")
  print(binary_matrix)
  return binary_matrix

def calculate_support(row_count, rows_total, min_support=0.25):
  support = row_count / rows_total
  if support >= min_support:
    return support
  else:
    return 0

def detect_frequent_itemsets(binary_matrix, min_support=0.25):
  rows_total = binary_matrix.shape[0]
  frequent_itemsets = []
  for i in range(binary_matrix.shape[1]):
    support = calculate_support(binary_matrix[:, i].sum(), rows_total, min_support)
    print(f"Column {i}: {binary_matrix[:, i].sum()}")
    if support > 0:
      frequent_itemsets.append((i + 1, support))
  return frequent_itemsets

frequent_itemsets = detect_frequent_itemsets(binary_matrix(test))
print(frequent_itemsets)







Binary matrix:
[[1 1 0 0 1]
 [1 0 0 1 1]
 [1 0 1 0 0]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [0 0 0 1 1]
 [1 0 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 0]]
Column 0: 7
Column 1: 4
Column 2: 5
Column 3: 4
Column 4: 7
[(1, 0.7), (2, 0.4), (3, 0.5), (4, 0.4), (5, 0.7)]
